---
# tasks file for httpd

- name: "Manage httpd Package"
  package:
    name: "{{ amdd_httpd_package_name }}"
    state: "{{ amdd_httpd_package_state }}"
  become: true
  notify: "Restart httpd Service"

- name: "Manage httpd Configuration"
  template:
    src: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}_httpd.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify: "Restart httpd Service"

- name: "Manage httpd Service"
  service:
    name: "{{ amdd_httpd_service_name }}"
    state: "{{ amdd_httpd_service_state }}"
    enabled: "{{ amdd_httpd_service_enabled }}"
  become: true

- name: "Manage httpd Firewall"
  firewalld:
    service: "{{ amdd_httpd_firewall_service }}"
    state: "{{ amdd_httpd_firewall_state }}"
    immediate: "{{ amdd_httpd_firewall_immediate }}"
    permanent: "{{ amdd_httpd_firewall_permanent }}"
  become: true
